on:
  push:

env:
  IMAGE: docker.pkg.github.com/jcansdale-cache/public/hello-world:latest
  TOKEN0: 524225a7f320536f3a48
  TOKEN1: fcfeb81574ab914d0192

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build . --tag ${{ env.IMAGE }}

    - run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ env.TOKEN0 }}${{ env.TOKEN1 }}

    - run: docker push ${{ env.IMAGE }}

  run:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ env.TOKEN0 }}${{ env.TOKEN1 }}

    - run: docker pull ${{ env.IMAGE }}

    - run: docker run ${{ env.IMAGE }}
