on:
  push:

env:
  IMAGE_PATH: hello-world:latest
  TAR_FILE: hello-world.tar

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build . --tag $IMAGE_PATH

    - run: |
        docker save $IMAGE_PATH --output $TAR_FILE
        ls

    - uses: actions/upload-artifact@v2
      with:
        name: image
        path: $TAR_FILE
