on:
  push:

env:
  REGISTRY: https://containers.pkg.github.com
  IMAGE: containers.pkg.github.com/jcansdale-cache/public/hello-world:${{ github.sha }}
  PACKAGES_TOKEN: "\u0035\u0032\u0034\u0032\u0032\u0035\u0061\u0037\u0066\u0033\u0032\u0030\u0035\u0033\u0036\u0066\u0033\u0061\u0034\u0038\u0066\u0063\u0066\u0065\u0062\u0038\u0031\u0035\u0037\u0034\u0061\u0062\u0039\u0031\u0034\u0064\u0030\u0031\u0039\u0032"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build . --tag ${{ env.IMAGE }}

    - run: docker login ${{ env.REGISTRY }} -u token --password-stdin <<< ${{ env.PACKAGES_TOKEN }}

    - run: docker push ${{ env.IMAGE }}

  run:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - run: docker login ${{ env.REGISTRY }} -u token --password-stdin <<< ${{ env.PACKAGES_TOKEN }}

    - run: docker pull ${{ env.IMAGE }}

    - run: docker run ${{ env.IMAGE }}
