on:
  push:

env:
  IMAGE: hello-world:latest
  TAR_FILE: hello-world.tar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build . --tag ${{ env.IMAGE }}

    - run: docker save ${{ env.IMAGE }} --output ${{ env.TAR_FILE }}

    - uses: actions/upload-artifact@v2
      with:
        name: name
        path: ${{ env.TAR_FILE }}

  run:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: name
        path: path

    - run: |
        ls image
        docker load --input ${{ env.TAR_FILE }}

    - run: docker run ${{ env.IMAGE }}
